# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(427, 275)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(379, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.iconLlabel = QtWidgets.QLabel(Form)
        self.iconLlabel.setMinimumSize(QtCore.QSize(61, 61))
        self.iconLlabel.setMaximumSize(QtCore.QSize(61, 61))
        self.iconLlabel.setStyleSheet("border-image: url(:/newPrefix/LiveMusic.png);")
        self.iconLlabel.setText("")
        self.iconLlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.iconLlabel.setObjectName("iconLlabel")
        self.gridLayout.addWidget(self.iconLlabel, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.nameLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.addressLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(11)
        self.addressLabel.setFont(font)
        self.addressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addressLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.addressLabel.setObjectName("addressLabel")
        self.verticalLayout.addWidget(self.addressLabel)
        self.listenLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setBold(False)
        font.setWeight(50)
        self.listenLabel.setFont(font)
        self.listenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.listenLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.listenLabel.setObjectName("listenLabel")
        self.verticalLayout.addWidget(self.listenLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "关于"))
        self.nameLabel.setText(_translate("Form", "<html><head/><body><p>虫草小王子<span style=\" vertical-align:sub;\">(叫我小王子就好)</span></p></body></html>"))
        self.addressLabel.setText(_translate("Form", "<html><head/><body><p>B站主页：https://space.bilibili.com/29418115</p></body></html>"))
        self.listenLabel.setText(_translate("Form", "Copyright © TLittlePrince. All rights reserved."))
import resource.QR_Code
