# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(247, 149)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.musicE = QtWidgets.QLineEdit(Form)
        self.musicE.setMinimumSize(QtCore.QSize(0, 30))
        self.musicE.setObjectName("musicE")
        self.verticalLayout.addWidget(self.musicE)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.artistE = QtWidgets.QLineEdit(Form)
        self.artistE.setMinimumSize(QtCore.QSize(0, 30))
        self.artistE.setObjectName("artistE")
        self.verticalLayout.addWidget(self.artistE)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加"))
        self.label.setText(_translate("Form", "歌曲"))
        self.label_2.setText(_translate("Form", "歌手"))
        self.pushButton.setText(_translate("Form", "确定"))
